#Clases, herencias y polimorfismos

###Definiciones (def)
Son operaciones globales en el notebook, operaciones sobre los argumentos

In [ ]:
#Vamos a crear una definición (que es una función integrada en python)

def Milanesi(a,b,c):
  x=a+b*c
  return x

In [ ]:
Milanesi(1,2,3)

7

In [ ]:
#Vamos a crear una definición que calcule la inversa de una matriz
import numpy as np

def Inv_Matrix (M):
  x=np.linalg.inv(M)
  return x

In [ ]:
A=np.array([[1,2,3],[0,1,0],[2,1,1]])
A


array([[1, 2, 3],
       [0, 1, 0],
       [2, 1, 1]])

In [ ]:
Inv_Matrix (A)


array([[-0.2, -0.2,  0.6],
       [ 0. ,  1. ,  0. ],
       [ 0.4, -0.6, -0.2]])

In [ ]:
A.shape

(3, 3)

In [ ]:
# np.random.seed --- esto es para fijar los elementos
np.random.seed (12)
y=np.random.randint(1,20,size=(2,2))
y

array([[12,  7],
       [18,  3]])

In [ ]:
Inv_Matrix(y)

array([[-0.03333333,  0.07777778],
       [ 0.2       , -0.13333333]])

In [ ]:
y.shape

(2, 2)