In [ ]:
import random
import numpy as np

random_integers = random.sample(range(1, 101), 100)

matrix = np.array(random_integers).reshape(10, 10)

print("Matriz original:")
print(matrix)

Matriz original:
[[ 22  71  74  50  91  61  94  29  97  68]
 [  7  90  83  10  59  49  28  70  95  20]
 [ 99  25  82  27  75  17  78  73  14  63]
 [ 52   5  57  66  19  45   9  40  37  42]
 [ 72  18  51  23  86  92  13  60  21  67]
 [ 62  98  93  69  53  81  85  39  76  43]
 [ 26  35   1  79  48  47  44  64  15  87]
 [ 33   6   3  30   2  16  77  46  11  12]
 [ 34  58  38  88  41  65  96  32  56  36]
 [ 89  54  24   4   8  84  31  80 100  55]]


Tarea: subir una base de datos de 10x10

In [ ]:
import random

# Lista de nombres de Tenistas
nombres = ["Alcaraz", "Djokovic", "Medvedev", "Tsitsipas", "Rune", "Sinner", "Ruud", "Rublev", "Fritz", "Tiafoe"]

# Generar matriz de datos aleatorios en este caso predicciones de juegos ganados en los proximos 10 años
matriz_datos = []
for _ in range(10):
    filas= [random.randint(10, 70) for _ in range(10)]
    matriz_datos.append(filas)

In [ ]:
import pandas as pd
matriz = pd.DataFrame(matriz_datos, columns=[f"AÑO {i+1}" for i in range(10)], index=nombres)
matriz

AÑO 1  AÑO 2  AÑO 3  AÑO 4  AÑO 5  AÑO 6  AÑO 7  AÑO 8  AÑO 9  \
Alcaraz       63     18     21     60     35     47     29     40     65   
Djokovic      23     37     18     21     29     59     26     53     33   
Medvedev      38     44     18     67     30     70     32     59     45   
Tsitsipas     52     68     21     41     22     42     32     69     68   
Rune          40     63     26     13     22     58     67     13     21   
Sinner        12     49     23     69     66     15     27     13     67   
Ruud          13     22     23     62     43     24     24     36     28   
Rublev        21     40     36     11     20     33     11     61     32   
Fritz         69     17     10     67     17     54     47     11     67   
Tiafoe        47     18     22     49     53     24     40     11     33   

           AÑO 10  
Alcaraz        22  
Djokovic       67  
Medvedev       55  
Tsitsipas      64  
Rune           23  
Sinner         33  
Ruud           22  
Rublev         61  
Fritz          33  
Tiafoe         31